"""Quiz generation service using DeepSeek.

Two-layer structure:
- Layer 1: Question bank (quiz_bank) — generated by AI, cached by content_hash
- Layer 2: Quiz attempt — sampled from bank, submitted by user

Stores results in Note.vocabulary with kind="quiz_bank" and kind="quiz".
"""

import logging
import random
import time
import uuid
from datetime import datetime, timezone
from typing import Optional

from app.agents import AgentContext, get_agent
from app.agents.normalizers import normalize_quiz_data
from app.config import DEEPSEEK_API_KEY
from app.models import Note, Session, Notebook, User, Task
from sqlalchemy.orm import Session as DBSessionType
from app.core.database import SessionLocal
from app.core.locks import get_session_task_lock
from app.core.task_runner import run_agent_task
from app.services.session_service import get_user_session as _get_session_by_user
from app.services.vector_service import _compute_session_content_hash
from app.services.note_utils import get_canonical_note_text
from app.services.state_service import set_running, set_ready, set_error, get_state
from app.services.vocabulary_service import (
    append_vocabulary_entry,
    delete_vocabulary_entries,
    save_vocabulary_entry,
)


logger = logging.getLogger(__name__)

TASK_TYPE = "agent_quiz"
ACTIVE_TASK_STATUSES = {"pending", "running"}
QUESTIONS_PER_QUIZ = 10
QUIZ_MODES = {"diagnostic", "review", "variant"}
QUIZ_MODE_TITLES = {
    "diagnostic": "课后诊断",
    "review": "复习后测验",
    "variant": "错题变式练习",
}
QUIZ_MODE_WEIGHTS = {
    "diagnostic": 0.3,
    "review": 1.0,
    "variant": 1.2,
}


def _normalize_quiz_mode(mode: str | None) -> str:
    normalized = (mode or "diagnostic").strip().lower()
    return normalized if normalized in QUIZ_MODES else "diagnostic"


def _question_knowledge_points(question: dict) -> list[str]:
    raw_points = question.get("knowledge_points", [])
    points: list[str] = []
    if isinstance(raw_points, list):
        for point in raw_points:
            text = str(point).strip()
            if text and text not in points:
                points.append(text[:40])
    if points:
        return points

    source = question.get("source", {})
    snippet = source.get("snippet", "") if isinstance(source, dict) else ""
    fallback = str(snippet or question.get("question", "") or "本节课核心知识").strip()
    return [fallback[:24] or "本节课核心知识"]


def _safe_question(question: dict) -> dict:
    return {
        "id": question.get("id"),
        "question": question.get("question"),
        "options": [
            {"id": o.get("id"), "text": o.get("text")}
            for o in question.get("options", [])
            if isinstance(o, dict)
        ],
        "knowledge_points": _question_knowledge_points(question),
        "difficulty": question.get("difficulty", "medium"),
        "question_type": question.get("question_type", "diagnostic"),
        "source_question_id": question.get("source_question_id"),
    }


# ── Vocabulary helpers: quiz_bank ──

def _get_quiz_bank_from_vocabulary(note: Note) -> Optional[dict]:
    """Read the quiz_bank entry from note.vocabulary.

    Normalizes the agent nested-data shape (data: {questions, title}) into the
    legacy flat shape (questions, title at top level) so downstream code stays
    unchanged.
    """
    if not isinstance(note.vocabulary, list):
        return None
    for item in note.vocabulary:
        if isinstance(item, dict) and item.get("kind") == "quiz_bank":
            if "data" in item and isinstance(item["data"], dict):
                return {
                    "kind": "quiz_bank",
                    "content_hash": item.get("content_hash", ""),
                    "generated_at": item.get("generated_at", ""),
                    "questions": item["data"].get("questions", []),
                    "title": item["data"].get("title", "本节课测验"),
                }
            return item
    return None


def _set_quiz_bank_in_vocabulary(
    db: DBSessionType, note: Note, bank_data: dict, content_hash: str
):
    """Set or replace the quiz_bank entry in note.vocabulary.

    Uses ``SELECT ... FOR UPDATE`` so concurrent agents do not overwrite other
    vocabulary entries.
    """
    entry = {
        "kind": "quiz_bank",
        "content_hash": content_hash,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "questions": bank_data["questions"],
    }
    save_vocabulary_entry(db, note.id, entry)


# ── Vocabulary helpers: quiz attempts ──

def _get_quizzes_from_vocabulary(note: Note) -> list[dict]:
    """Read all quiz attempt entries from note.vocabulary."""
    if not isinstance(note.vocabulary, list):
        return []
    return [
        item for item in note.vocabulary
        if isinstance(item, dict) and item.get("kind") == "quiz"
    ]


def _add_quiz_to_vocabulary(db: DBSessionType, note: Note, quiz_entry: dict):
    """Add a quiz attempt entry to note.vocabulary."""
    append_vocabulary_entry(db, note.id, quiz_entry)


def _remove_quiz_from_vocabulary(db: DBSessionType, note: Note, quiz_id: str):
    """Remove a specific quiz attempt from note.vocabulary by quiz_id."""
    delete_vocabulary_entries(
        db,
        note.id,
        lambda item: item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id,
    )


def _get_quiz_from_vocabulary(note: Note, quiz_id: str) -> Optional[dict]:
    """Read a specific quiz attempt from note.vocabulary by quiz_id."""
    if not isinstance(note.vocabulary, list):
        return None
    for item in note.vocabulary:
        if isinstance(item, dict) and item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id:
            return item
    return None


def _update_quiz_in_vocabulary(
    db: DBSessionType, note: Note, quiz_id: str, updated_entry: dict
):
    """Replace a quiz entry in vocabulary (for saving submissions)."""
    save_vocabulary_entry(
        db,
        note.id,
        updated_entry,
        replace_predicate=lambda item: (
            item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id
        ),
    )


def _sample_questions_for_attempt(all_questions: list[dict], quizzes: list[dict], count: int, mode: str = "diagnostic") -> list[dict]:
    """Sample questions with review-friendly priority.

    Priority:
    diagnostic: broad coverage, prefer unused questions.
    review: wrong questions, then unused questions, then used questions.
    variant: questions sharing knowledge points with historical mistakes, excluding the original wrong questions.
    """
    mode = _normalize_quiz_mode(mode)
    by_id = {q.get("id"): q for q in all_questions if isinstance(q, dict) and q.get("id")}
    used_ids: set[str] = set()
    wrong_ids: set[str] = set()
    correct_ids: set[str] = set()
    wrong_points: set[str] = set()

    for quiz in quizzes:
        snapshot = quiz.get("questions_snapshot", [])
        questions_by_id = {
            q.get("id"): q
            for q in snapshot
            if isinstance(q, dict) and q.get("id")
        }
        for q in snapshot:
            if isinstance(q, dict) and q.get("id"):
                used_ids.add(q["id"])

        submission = quiz.get("submission")
        if isinstance(submission, dict):
            for result in submission.get("results", []):
                if not isinstance(result, dict) or not result.get("question_id"):
                    continue
                qid = result["question_id"]
                if result.get("correct") is False:
                    wrong_ids.add(qid)
                    for point in _question_knowledge_points(questions_by_id.get(qid, {})):
                        wrong_points.add(point)
                elif result.get("correct") is True:
                    correct_ids.add(qid)

    def pick(ids: list[str], remaining: int) -> list[dict]:
        candidates = [by_id[qid] for qid in ids if qid in by_id]
        random.shuffle(candidates)
        return candidates[:remaining]

    def pick_balanced(ids: list[str], remaining: int) -> list[dict]:
        buckets: dict[str, list[str]] = {}
        for qid in ids:
            if qid not in by_id:
                continue
            point = _question_knowledge_points(by_id[qid])[0]
            buckets.setdefault(point, []).append(qid)
        for bucket in buckets.values():
            random.shuffle(bucket)
        selected_ids: list[str] = []
        while len(selected_ids) < remaining and buckets:
            for point in list(buckets.keys()):
                bucket = buckets[point]
                if bucket:
                    selected_ids.append(bucket.pop())
                    if len(selected_ids) >= remaining:
                        break
                if not bucket:
                    buckets.pop(point, None)
        return [by_id[qid] for qid in selected_ids if qid in by_id]

    selected: list[dict] = []
    selected_ids: set[str] = set()

    if mode == "diagnostic":
        priority_groups = (
            [qid for qid in by_id if qid not in used_ids],
            list(by_id.keys()),
        )
        first_group = True
    elif mode == "variant":
        variant_ids = [
            qid for qid, q in by_id.items()
            if qid not in wrong_ids
            and any(point in wrong_points for point in _question_knowledge_points(q))
        ]
        priority_groups = (
            variant_ids,
            [qid for qid in by_id if qid not in wrong_ids and qid not in used_ids],
            [qid for qid in by_id if qid not in wrong_ids],
        )
        first_group = False
    else:
        priority_groups = (
            list(wrong_ids),
            [qid for qid in by_id if qid not in used_ids],
            [qid for qid in by_id if qid not in wrong_ids],
            [qid for qid in by_id if qid not in correct_ids],
        )
        first_group = False

    for ids in priority_groups:
        remaining = count - len(selected)
        if remaining <= 0:
            break
        filtered_ids = [qid for qid in ids if qid not in selected_ids]
        picked = pick_balanced(filtered_ids, remaining) if first_group else pick(filtered_ids, remaining)
        first_group = False
        for q in picked:
            selected.append(q)
            selected_ids.add(q["id"])

    return selected


# ── Session ownership ──

def _get_session_for_user(session_id: str, user: User, db: DBSessionType) -> Session | None:
    return _get_session_by_user(db, session_id, user.id)


# ── Async task helpers ──

def _get_latest_task(session_id: str, db: DBSessionType) -> Task | None:
    return db.query(Task).filter(
        Task.session_id == session_id,
        Task.task_type == TASK_TYPE,
    ).order_by(Task.created_at.desc()).first()


def _get_active_task(session_id: str, db: DBSessionType) -> Task | None:
    return db.query(Task).filter(
        Task.session_id == session_id,
        Task.task_type == TASK_TYPE,
        Task.status.in_(ACTIVE_TASK_STATUSES),
    ).order_by(Task.created_at.desc()).first()


def _task_payload(task: Task | None) -> dict:
    if not task:
        return {}
    return {
        "task_id": task.id,
        "progress": float(task.progress or 0.0),
        "error": task.error_message,
    }


# ── Core: generate question bank via QuizAgent ──

def _generate_question_bank_sync(session_id: str, user: User, db: DBSessionType, task: Task | None = None) -> dict:
    """Generate a question bank via the QuizAgent."""
    if not DEEPSEEK_API_KEY:
        raise ValueError("未配置 DEEPSEEK_API_KEY，无法生成测验")

    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")

    notebook = db.query(Notebook).filter(Notebook.id == session.notebook_id).first()
    if not notebook:
        raise ValueError("Notebook not found")

    content_text = get_canonical_note_text(note, include_ppt=True)
    if not content_text.strip():
        raise ValueError("No indexable content in note")

    agent = get_agent("quiz")
    ctx = AgentContext(
        session_id=session_id,
        user=user,
        db=db,
        note=note,
        session=session,
        notebook=notebook,
        task=task,
    )
    result = agent.run(ctx)
    if not result.success:
        raise ValueError(result.error_message or "题库生成失败")

    return result.data if result.data else {}


# ── Async task runner ──

def _run_quiz_bank_task(task_id: str, session_id: str, user_id: str):
    db = SessionLocal()
    started = time.monotonic()
    try:
        task = db.query(Task).filter(Task.id == task_id).first()
        user = db.query(User).filter(User.id == user_id).first()
        if not task or not user:
            return

        task.status = "running"
        task.progress = 0.1
        task.error_message = None
        db.commit()

        set_running(db, session_id, "quiz_bank", progress=0.1)

        _generate_question_bank_sync(session_id, user, db, task=task)

        # Re-fetch note before saving to reduce race window with other agents
        note = db.query(Note).filter(Note.session_id == session_id).first()
        if note:
            db.refresh(note)

        task = db.query(Task).filter(Task.id == task_id).first()
        if task:
            task.status = "success"
            task.progress = 1.0
            task.error_message = None
            current_hash = _compute_session_content_hash(note) if note else ""
            set_ready(db, session_id, "quiz_bank", content_hash=current_hash)
            db.commit()
        logger.info(
            "quiz_bank_task_success task_id=%s session_id=%s elapsed_ms=%s",
            task_id, session_id, int((time.monotonic() - started) * 1000),
        )
    except Exception as e:
        db.rollback()
        task = db.query(Task).filter(Task.id == task_id).first()
        if task:
            task.status = "error"
            task.progress = 1.0
            task.error_message = str(e)
            db.commit()
        set_error(db, session_id, "quiz_bank", error_message=str(e))
        logger.exception(
            "quiz_bank_task_failed task_id=%s session_id=%s",
            task_id, session_id,
        )
    finally:
        db.close()


# ── Bank status ──

def get_bank_status(session_id: str, user: User, db: DBSessionType) -> dict:
    """Get question bank status for a session."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    has_content = bool(note and get_canonical_note_text(note, include_ppt=True).strip())

    if not has_content:
        return {"session_id": session_id, "status": "empty", "question_count": 0, "task_id": None, "progress": 0, "error": None}

    bank_entry = _get_quiz_bank_from_vocabulary(note) if note else None
    active_task = _get_active_task(session_id, db)

    if active_task:
        return {
            "session_id": session_id,
            "status": "generating",
            "question_count": len(bank_entry.get("questions", [])) if bank_entry else 0,
            **_task_payload(active_task),
        }

    if not bank_entry:
        latest_task = _get_latest_task(session_id, db)
        if latest_task and latest_task.status == "error":
            return {
                "session_id": session_id,
                "status": "error",
                "question_count": 0,
                **_task_payload(latest_task),
            }
        return {"session_id": session_id, "status": "not_generated", "question_count": 0, "task_id": None, "progress": 0, "error": None}

    # Check stale
    current_hash = _compute_session_content_hash(note)
    bank_hash = bank_entry.get("content_hash", "")
    if current_hash != bank_hash:
        return {
            "session_id": session_id,
            "status": "stale",
            "question_count": len(bank_entry.get("questions", [])),
            "task_id": None,
            "progress": 0,
            "error": None,
        }

    current_state = get_state(db, session_id, "quiz_bank")
    if current_state and current_state.status != "ready":
        set_ready(db, session_id, "quiz_bank")

    return {
        "session_id": session_id,
        "status": "ready",
        "question_count": len(bank_entry.get("questions", [])),
        "task_id": None,
        "progress": 1.0,
        "error": None,
    }


# ── Start/rebuild bank ──

def start_bank_generation(session_id: str, user: User, db: DBSessionType, force: bool = False) -> dict:
    """Start or reuse an async question bank generation task.

    If force=True, ignore the "ready" status and start a new task (for manual rebuild).
    If force=False, return ready status if bank is already valid.
    Always reuses an active (pending/running) task regardless of force.
    """
    if not DEEPSEEK_API_KEY:
        raise ValueError("未配置 DEEPSEEK_API_KEY，无法生成测验")

    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")
    content_text = get_canonical_note_text(note, include_ppt=True)
    if not content_text.strip():
        raise ValueError("No indexable content in note")

    with get_session_task_lock(session_id, TASK_TYPE):
        # Re-check inside the lock to close the race window.
        db.expire_all()

        # Always reuse active task if one exists
        active_task = _get_active_task(session_id, db)
        if active_task:
            return {
                "session_id": session_id,
                "status": "generating",
                "question_count": 0,
                **_task_payload(active_task),
            }

        # If not forced and bank is ready, return it
        if not force:
            bank_status = get_bank_status(session_id, user, db)
            if bank_status["status"] == "ready":
                return bank_status

        # Create new task
        task = Task(
            session_id=session_id,
            task_type=TASK_TYPE,
            status="pending",
            progress=0.0,
            error_message=None,
        )
        db.add(task)
        db.commit()
        db.refresh(task)

    run_agent_task(
        target=lambda: _run_quiz_bank_task(task.id, session_id, user.id),
        daemon=True,
    )
    logger.info(
        "quiz_bank_task_started task_id=%s session_id=%s user_id=%s",
        task.id, session_id, user.id,
    )

    return {
        "session_id": session_id,
        "status": "generating",
        "question_count": 0,
        **_task_payload(task),
    }


# ── Generate quiz attempt (from bank, no AI call) ──

def generate_quiz(session_id: str, user: User, db: DBSessionType, mode: str = "diagnostic") -> dict:
    """Generate a quiz attempt by sampling from the question bank.

    If bank is not ready, returns status info so the frontend can trigger bank generation.
    Does NOT call AI — only samples from existing bank.
    """
    mode = _normalize_quiz_mode(mode)
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")

    bank_entry = _get_quiz_bank_from_vocabulary(note)
    if not bank_entry or not bank_entry.get("questions"):
        # Need to generate bank first — return status so frontend can trigger
        return {"status": "need_bank", "message": "请先生成题库"}

    # Check stale
    current_hash = _compute_session_content_hash(note)
    if current_hash != bank_entry.get("content_hash", ""):
        return {"status": "stale", "message": "笔记内容已变化，请重新生成题库"}

    # Sample questions from bank
    all_questions = bank_entry["questions"]
    count = min(QUESTIONS_PER_QUIZ, len(all_questions))
    sampled = _sample_questions_for_attempt(all_questions, _get_quizzes_from_vocabulary(note), count, mode)
    if mode == "variant" and not sampled:
        return {"status": "no_mistakes", "message": "暂无可用于变式练习的错题知识点"}

    quiz_id = str(uuid.uuid4())

    # Save full question snapshot in the attempt so it's immune to bank rebuilds.
    # The snapshot includes answers; we strip them when returning to the frontend.
    questions_snapshot = []
    for q in sampled:
        snapshot_q = dict(q)
        snapshot_q["knowledge_points"] = _question_knowledge_points(snapshot_q)
        snapshot_q["difficulty"] = snapshot_q.get("difficulty", "medium")
        snapshot_q["question_type"] = mode
        questions_snapshot.append(snapshot_q)

    quiz_entry = {
        "kind": "quiz",
        "quiz_id": quiz_id,
        "mode": mode,
        "title": QUIZ_MODE_TITLES[mode],
        "bank_hash": bank_entry.get("content_hash", ""),
        "questions_snapshot": questions_snapshot,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "submission": None,
    }
    _add_quiz_to_vocabulary(db, note, quiz_entry)

    # Return questions WITHOUT answers for the taking-quiz view
    safe_questions = [_safe_question(q) for q in questions_snapshot]

    return {
        "quiz_id": quiz_id,
        "title": QUIZ_MODE_TITLES[mode],
        "mode": mode,
        "questions": safe_questions,
    }


# ── List quizzes (without answers) ──

def get_session_quizzes(session_id: str, user: User, db: DBSessionType) -> list[dict]:
    """Return list of all quiz attempts for a session, without answers."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        return []

    quizzes = _get_quizzes_from_vocabulary(note)
    result = []
    for entry in quizzes:
        snapshot = entry.get("questions_snapshot", [])
        submission = entry.get("submission")

        # Build safe questions (no answers)
        safe_questions = []
        for q in snapshot:
            safe_questions.append(_safe_question(q))

        score_summary = None
        if submission:
            score_summary = {
                "score": submission.get("score", 0),
                "total": submission.get("total", 0),
                "percentage": submission.get("percentage", 0),
            }

        result.append({
            "quiz_id": entry.get("quiz_id"),
            "title": entry.get("title") or QUIZ_MODE_TITLES.get(entry.get("mode", "diagnostic"), "本节课测验"),
            "mode": _normalize_quiz_mode(entry.get("mode")),
            "question_count": len(snapshot),
            "questions": safe_questions,
            "generated_at": entry.get("generated_at"),
            "submitted": submission is not None,
            "score": score_summary,
        })

    return result


# ── Quiz detail ──

def get_quiz_detail(session_id: str, quiz_id: str, user: User, db: DBSessionType) -> dict:
    """Return quiz detail. If not submitted, strip answers. If submitted, return full detail."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("Quiz not found")

    entry = _get_quiz_from_vocabulary(note, quiz_id)
    if not entry:
        raise ValueError("Quiz not found")

    snapshot = entry.get("questions_snapshot", [])
    submission = entry.get("submission")

    if submission:
        # Submitted — return full detail with answers and explanations
        return {
            "quiz_id": entry.get("quiz_id"),
            "title": entry.get("title") or QUIZ_MODE_TITLES.get(entry.get("mode", "diagnostic"), "本节课测验"),
            "mode": _normalize_quiz_mode(entry.get("mode")),
            "questions": snapshot,
            "generated_at": entry.get("generated_at"),
            "submission": submission,
        }
    else:
        # Not submitted — strip answers
        safe_questions = []
        for q in snapshot:
            safe_questions.append(_safe_question(q))

        return {
            "quiz_id": entry.get("quiz_id"),
            "title": entry.get("title") or QUIZ_MODE_TITLES.get(entry.get("mode", "diagnostic"), "本节课测验"),
            "mode": _normalize_quiz_mode(entry.get("mode")),
            "questions": safe_questions,
            "generated_at": entry.get("generated_at"),
            "submission": None,
        }


# ── Submit quiz answers ──

def submit_quiz_answers(session_id: str, quiz_id: str, user: User, db: DBSessionType, answers: dict) -> dict:
    """Submit answers for a quiz attempt. Calculate score using bank answers."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("Quiz not found")

    entry = _get_quiz_from_vocabulary(note, quiz_id)
    if not entry:
        raise ValueError("Quiz not found")

    # If already submitted, return existing results
    if entry.get("submission"):
        sub = entry["submission"]
        return {
            "score": sub.get("score", 0),
            "total": sub.get("total", 0),
            "percentage": sub.get("percentage", 0),
            "results": sub.get("results", []),
        }

    # Get answers from snapshot (immune to bank rebuilds)
    snapshot = entry.get("questions_snapshot", [])

    correct_count = 0
    results = []
    for q in snapshot:
        qid = q.get("id")
        correct_answer = q.get("answer", "")
        selected = answers.get(qid, "")
        is_correct = selected == correct_answer
        if is_correct:
            correct_count += 1

        results.append({
            "question_id": qid,
            "correct": is_correct,
            "selected": selected,
            "answer": correct_answer,
            "explanation": q.get("explanation", ""),
            "knowledge_points": _question_knowledge_points(q),
            "difficulty": q.get("difficulty", "medium"),
        })

    total = len(snapshot)
    percentage = round(correct_count / total * 100, 1) if total > 0 else 0

    # Save submission
    updated_entry = dict(entry)
    updated_entry["submission"] = {
        "answers": answers,
        "mode": _normalize_quiz_mode(entry.get("mode")),
        "score": correct_count,
        "total": total,
        "percentage": percentage,
        "results": results,
        "submitted_at": datetime.now(timezone.utc).isoformat(),
    }
    _update_quiz_in_vocabulary(db, note, quiz_id, updated_entry)

    return {
        "score": correct_count,
        "total": total,
        "percentage": percentage,
        "results": results,
    }


# ── Knowledge point mastery ──

def get_quiz_mastery(session_id: str, user: User, db: DBSessionType) -> dict:
    """Return weighted mastery stats grouped by question knowledge point."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        return {"session_id": session_id, "knowledge_points": [], "summary": {"weak_count": 0, "pending_review_count": 0}}

    stats: dict[str, dict] = {}
    quizzes = _get_quizzes_from_vocabulary(note)

    for quiz in quizzes:
        submission = quiz.get("submission")
        if not isinstance(submission, dict):
            continue
        mode = _normalize_quiz_mode(submission.get("mode") or quiz.get("mode"))
        weight = QUIZ_MODE_WEIGHTS.get(mode, 1.0)
        snapshot = quiz.get("questions_snapshot", [])
        questions_by_id = {
            q.get("id"): q
            for q in snapshot
            if isinstance(q, dict) and q.get("id")
        }

        for result in submission.get("results", []):
            if not isinstance(result, dict):
                continue
            qid = result.get("question_id")
            question = questions_by_id.get(qid, {})
            points = result.get("knowledge_points")
            if not isinstance(points, list) or not points:
                points = _question_knowledge_points(question)
            for raw_point in points:
                point = str(raw_point).strip()
                if not point:
                    continue
                item = stats.setdefault(point, {
                    "knowledge_point": point,
                    "attempts": 0,
                    "correct": 0,
                    "wrong": 0,
                    "weighted_total": 0.0,
                    "weighted_correct": 0.0,
                    "diagnostic_wrong": 0,
                    "last_mode": mode,
                })
                item["attempts"] += 1
                item["weighted_total"] += weight
                item["last_mode"] = mode
                if result.get("correct"):
                    item["correct"] += 1
                    item["weighted_correct"] += weight
                else:
                    item["wrong"] += 1
                    if mode == "diagnostic":
                        item["diagnostic_wrong"] += 1

    knowledge_points = []
    for item in stats.values():
        total = item["weighted_total"]
        mastery = round(item["weighted_correct"] / total * 100, 1) if total else 0
        pending_review = item["diagnostic_wrong"] > 0 and item["weighted_total"] < 1
        weak = (item["wrong"] >= 2 and mastery < 70) or (total >= 1 and mastery < 60)
        knowledge_points.append({
            "knowledge_point": item["knowledge_point"],
            "mastery": mastery,
            "attempts": item["attempts"],
            "correct": item["correct"],
            "wrong": item["wrong"],
            "pending_review": pending_review,
            "weak": weak,
            "last_mode": item["last_mode"],
        })

    knowledge_points.sort(key=lambda x: (x["mastery"], -x["wrong"], x["knowledge_point"]))
    return {
        "session_id": session_id,
        "knowledge_points": knowledge_points,
        "summary": {
            "weak_count": sum(1 for item in knowledge_points if item["weak"]),
            "pending_review_count": sum(1 for item in knowledge_points if item["pending_review"]),
        },
    }


# ── Delete quiz attempt ──

def delete_quiz(session_id: str, quiz_id: str, user: User, db: DBSessionType) -> dict:
    """Delete a specific quiz attempt (not the bank)."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if note:
        _remove_quiz_from_vocabulary(db, note, quiz_id)

    return {"session_id": session_id, "quiz_id": quiz_id, "status": "deleted"}
