"""Quiz generation service using DeepSeek.

Two-layer structure:
- Layer 1: Question bank (quiz_bank) — generated by AI, cached by content_hash
- Layer 2: Quiz attempt — sampled from bank, submitted by user

Stores results in Note.vocabulary with kind="quiz_bank" and kind="quiz".
"""

import logging
import random
import threading
import time
import uuid
from datetime import datetime, timezone
from typing import Optional

from app.agents import AgentContext, get_agent
from app.agents.normalizers import normalize_quiz_data
from app.config import DEEPSEEK_API_KEY
from openai import OpenAI  # noqa: F401  kept for test compatibility
from app.models import Note, Session, Notebook, User, Task
from sqlalchemy.orm import Session as DBSessionType
from app.core.database import SessionLocal
from app.core.task_runner import run_agent_task
from app.services.vector_service import _compute_session_content_hash
from app.services.state_service import set_running, set_ready, set_error, get_state
from app.services.note_utils import get_canonical_note_text


logger = logging.getLogger(__name__)

TASK_TYPE = "agent_quiz"
ACTIVE_TASK_STATUSES = {"pending", "running"}
QUESTIONS_PER_QUIZ = 10

# Per-(session_id, task_type) lock to prevent races when checking for active
# tasks and creating new ones.
_START_LOCKS: dict[str, threading.Lock] = {}
_START_LOCKS_GUARD = threading.Lock()


def _get_start_lock(session_id: str, task_type: str) -> threading.Lock:
    key = f"{session_id}:{task_type}"
    lock = _START_LOCKS.get(key)
    if lock is None:
        with _START_LOCKS_GUARD:
            lock = _START_LOCKS.get(key)
            if lock is None:
                lock = threading.Lock()
                _START_LOCKS[key] = lock
    return lock


# ── Vocabulary helpers: quiz_bank ──

def _get_quiz_bank_from_vocabulary(note: Note) -> Optional[dict]:
    """Read the quiz_bank entry from note.vocabulary.

    Normalizes the agent nested-data shape (data: {questions, title}) into the
    legacy flat shape (questions, title at top level) so downstream code stays
    unchanged.
    """
    if not isinstance(note.vocabulary, list):
        return None
    for item in note.vocabulary:
        if isinstance(item, dict) and item.get("kind") == "quiz_bank":
            if "data" in item and isinstance(item["data"], dict):
                return {
                    "kind": "quiz_bank",
                    "content_hash": item.get("content_hash", ""),
                    "generated_at": item.get("generated_at", ""),
                    "questions": item["data"].get("questions", []),
                    "title": item["data"].get("title", "本节课测验"),
                }
            return item
    return None


def _set_quiz_bank_in_vocabulary(note: Note, bank_data: dict, content_hash: str):
    """Set or replace the quiz_bank entry in note.vocabulary."""
    existing = note.vocabulary if isinstance(note.vocabulary, list) else []
    next_items = [item for item in existing if not (isinstance(item, dict) and item.get("kind") == "quiz_bank")]
    next_items.append({
        "kind": "quiz_bank",
        "content_hash": content_hash,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "questions": bank_data["questions"],
    })
    note.vocabulary = next_items


# ── Vocabulary helpers: quiz attempts ──

def _get_quizzes_from_vocabulary(note: Note) -> list[dict]:
    """Read all quiz attempt entries from note.vocabulary."""
    if not isinstance(note.vocabulary, list):
        return []
    return [
        item for item in note.vocabulary
        if isinstance(item, dict) and item.get("kind") == "quiz"
    ]


def _add_quiz_to_vocabulary(note: Note, quiz_entry: dict):
    """Add a quiz attempt entry to note.vocabulary."""
    existing = note.vocabulary if isinstance(note.vocabulary, list) else []
    next_items = list(existing)
    next_items.append(quiz_entry)
    note.vocabulary = next_items


def _remove_quiz_from_vocabulary(note: Note, quiz_id: str):
    """Remove a specific quiz attempt from note.vocabulary by quiz_id."""
    existing = note.vocabulary if isinstance(note.vocabulary, list) else []
    next_items = [
        item for item in existing
        if not (isinstance(item, dict) and item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id)
    ]
    note.vocabulary = next_items


def _get_quiz_from_vocabulary(note: Note, quiz_id: str) -> Optional[dict]:
    """Read a specific quiz attempt from note.vocabulary by quiz_id."""
    if not isinstance(note.vocabulary, list):
        return None
    for item in note.vocabulary:
        if isinstance(item, dict) and item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id:
            return item
    return None


def _update_quiz_in_vocabulary(note: Note, quiz_id: str, updated_entry: dict):
    """Replace a quiz entry in vocabulary (for saving submissions)."""
    existing = note.vocabulary if isinstance(note.vocabulary, list) else []
    next_items = []
    for item in existing:
        if isinstance(item, dict) and item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id:
            next_items.append(updated_entry)
        else:
            next_items.append(item)
    note.vocabulary = next_items


def _sample_questions_for_attempt(all_questions: list[dict], quizzes: list[dict], count: int) -> list[dict]:
    """Sample questions with review-friendly priority.

    Priority:
    1. Previously answered wrong questions.
    2. Questions not used in submitted attempts yet.
    3. Previously answered correctly / already used questions.
    """
    by_id = {q.get("id"): q for q in all_questions if isinstance(q, dict) and q.get("id")}
    used_ids: set[str] = set()
    wrong_ids: set[str] = set()

    for quiz in quizzes:
        snapshot = quiz.get("questions_snapshot", [])
        for q in snapshot:
            if isinstance(q, dict) and q.get("id"):
                used_ids.add(q["id"])

        submission = quiz.get("submission")
        if isinstance(submission, dict):
            for result in submission.get("results", []):
                if isinstance(result, dict) and result.get("correct") is False and result.get("question_id"):
                    wrong_ids.add(result["question_id"])

    def pick(ids: list[str], remaining: int) -> list[dict]:
        candidates = [by_id[qid] for qid in ids if qid in by_id]
        random.shuffle(candidates)
        return candidates[:remaining]

    selected: list[dict] = []
    selected_ids: set[str] = set()

    for ids in (
        list(wrong_ids),
        [qid for qid in by_id if qid not in used_ids],
        [qid for qid in by_id if qid not in wrong_ids],
    ):
        remaining = count - len(selected)
        if remaining <= 0:
            break
        for q in pick([qid for qid in ids if qid not in selected_ids], remaining):
            selected.append(q)
            selected_ids.add(q["id"])

    return selected


# ── Content extraction ──

def _extract_content_for_prompt(note: Note) -> str:
    """Extract all note content into a single text for the AI prompt.

    Uses the canonical note text (transcript + notes + PPT) so that user edits
    and deletions are respected and the same source is used across agents.
    """
    text = get_canonical_note_text(note, include_ppt=True)
    if text.strip():
        return text.strip()

    # Fallback: raw content if canonical extraction returned nothing.
    if note.content:
        return note.content.strip()

    return ""


# ── Session ownership ──

def _get_session_for_user(session_id: str, user: User, db: DBSessionType) -> Session | None:
    return db.query(Session).filter(
        Session.id == session_id
    ).join(Notebook).filter(Notebook.user_id == user.id).first()


# ── Async task helpers ──

def _get_latest_task(session_id: str, db: DBSessionType) -> Task | None:
    return db.query(Task).filter(
        Task.session_id == session_id,
        Task.task_type == TASK_TYPE,
    ).order_by(Task.created_at.desc()).first()


def _get_active_task(session_id: str, db: DBSessionType) -> Task | None:
    return db.query(Task).filter(
        Task.session_id == session_id,
        Task.task_type == TASK_TYPE,
        Task.status.in_(ACTIVE_TASK_STATUSES),
    ).order_by(Task.created_at.desc()).first()


def _task_payload(task: Task | None) -> dict:
    if not task:
        return {}
    return {
        "task_id": task.id,
        "progress": float(task.progress or 0.0),
        "error": task.error_message,
    }


# ── Core: generate question bank via QuizAgent ──

def _generate_question_bank_sync(session_id: str, user: User, db: DBSessionType, task: Task | None = None) -> dict:
    """Generate a question bank via the QuizAgent."""
    if not DEEPSEEK_API_KEY:
        raise ValueError("未配置 DEEPSEEK_API_KEY，无法生成测验")

    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")

    notebook = db.query(Notebook).filter(Notebook.id == session.notebook_id).first()
    if not notebook:
        raise ValueError("Notebook not found")

    content_text = _extract_content_for_prompt(note)
    if not content_text.strip():
        raise ValueError("No indexable content in note")

    agent = get_agent("quiz")
    ctx = AgentContext(
        session_id=session_id,
        user=user,
        db=db,
        note=note,
        session=session,
        notebook=notebook,
        task=task,
    )
    result = agent.run(ctx)
    if not result.success:
        raise ValueError(result.error_message or "题库生成失败")

    return result.data if result.data else {}


# ── Async task runner ──

def _run_quiz_bank_task(task_id: str, session_id: str, user_id: str):
    db = SessionLocal()
    started = time.monotonic()
    try:
        task = db.query(Task).filter(Task.id == task_id).first()
        user = db.query(User).filter(User.id == user_id).first()
        if not task or not user:
            return

        task.status = "running"
        task.progress = 0.1
        task.error_message = None
        db.commit()

        set_running(db, session_id, "quiz_bank", progress=0.1)

        _generate_question_bank_sync(session_id, user, db, task=task)

        # Re-fetch note before saving to reduce race window with other agents
        note = db.query(Note).filter(Note.session_id == session_id).first()
        if note:
            db.refresh(note)

        task = db.query(Task).filter(Task.id == task_id).first()
        if task:
            task.status = "success"
            task.progress = 1.0
            task.error_message = None
            current_hash = _compute_session_content_hash(note) if note else ""
            set_ready(db, session_id, "quiz_bank", content_hash=current_hash)
            db.commit()
        logger.info(
            "quiz_bank_task_success task_id=%s session_id=%s elapsed_ms=%s",
            task_id, session_id, int((time.monotonic() - started) * 1000),
        )
    except Exception as e:
        db.rollback()
        task = db.query(Task).filter(Task.id == task_id).first()
        if task:
            task.status = "error"
            task.progress = 1.0
            task.error_message = str(e)
            db.commit()
        set_error(db, session_id, "quiz_bank", error_message=str(e))
        logger.exception(
            "quiz_bank_task_failed task_id=%s session_id=%s",
            task_id, session_id,
        )
    finally:
        db.close()


# ── Bank status ──

def get_bank_status(session_id: str, user: User, db: DBSessionType) -> dict:
    """Get question bank status for a session."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    has_content = bool(note and (note.content or note.transcript or note.ppt_images or note.layout_blocks))

    if not has_content:
        return {"session_id": session_id, "status": "empty", "question_count": 0, "task_id": None, "progress": 0, "error": None}

    bank_entry = _get_quiz_bank_from_vocabulary(note) if note else None
    active_task = _get_active_task(session_id, db)

    if active_task:
        return {
            "session_id": session_id,
            "status": "generating",
            "question_count": len(bank_entry.get("questions", [])) if bank_entry else 0,
            **_task_payload(active_task),
        }

    if not bank_entry:
        latest_task = _get_latest_task(session_id, db)
        if latest_task and latest_task.status == "error":
            return {
                "session_id": session_id,
                "status": "error",
                "question_count": 0,
                **_task_payload(latest_task),
            }
        return {"session_id": session_id, "status": "not_generated", "question_count": 0, "task_id": None, "progress": 0, "error": None}

    # Check stale
    current_hash = _compute_session_content_hash(note)
    bank_hash = bank_entry.get("content_hash", "")
    if current_hash != bank_hash:
        return {
            "session_id": session_id,
            "status": "stale",
            "question_count": len(bank_entry.get("questions", [])),
            "task_id": None,
            "progress": 0,
            "error": None,
        }

    current_state = get_state(db, session_id, "quiz_bank")
    if current_state and current_state.status != "ready":
        set_ready(db, session_id, "quiz_bank")

    return {
        "session_id": session_id,
        "status": "ready",
        "question_count": len(bank_entry.get("questions", [])),
        "task_id": None,
        "progress": 1.0,
        "error": None,
    }


# ── Start/rebuild bank ──

def start_bank_generation(session_id: str, user: User, db: DBSessionType, force: bool = False) -> dict:
    """Start or reuse an async question bank generation task.

    If force=True, ignore the "ready" status and start a new task (for manual rebuild).
    If force=False, return ready status if bank is already valid.
    Always reuses an active (pending/running) task regardless of force.
    """
    if not DEEPSEEK_API_KEY:
        raise ValueError("未配置 DEEPSEEK_API_KEY，无法生成测验")

    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")
    content_text = _extract_content_for_prompt(note)
    if not content_text.strip():
        raise ValueError("No indexable content in note")

    with _get_start_lock(session_id, TASK_TYPE):
        # Re-check inside the lock to close the race window.
        db.expire_all()

        # Always reuse active task if one exists
        active_task = _get_active_task(session_id, db)
        if active_task:
            return {
                "session_id": session_id,
                "status": "generating",
                "question_count": 0,
                **_task_payload(active_task),
            }

        # If not forced and bank is ready, return it
        if not force:
            bank_status = get_bank_status(session_id, user, db)
            if bank_status["status"] == "ready":
                return bank_status

        # Create new task
        task = Task(
            session_id=session_id,
            task_type=TASK_TYPE,
            status="pending",
            progress=0.0,
            error_message=None,
        )
        db.add(task)
        db.commit()
        db.refresh(task)

    run_agent_task(
        target=lambda: _run_quiz_bank_task(task.id, session_id, user.id),
        daemon=True,
    )
    logger.info(
        "quiz_bank_task_started task_id=%s session_id=%s user_id=%s",
        task.id, session_id, user.id,
    )

    return {
        "session_id": session_id,
        "status": "generating",
        "question_count": 0,
        **_task_payload(task),
    }


# ── Generate quiz attempt (from bank, no AI call) ──

def generate_quiz(session_id: str, user: User, db: DBSessionType) -> dict:
    """Generate a quiz attempt by sampling from the question bank.

    If bank is not ready, returns status info so the frontend can trigger bank generation.
    Does NOT call AI — only samples from existing bank.
    """
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")

    bank_entry = _get_quiz_bank_from_vocabulary(note)
    if not bank_entry or not bank_entry.get("questions"):
        # Need to generate bank first — return status so frontend can trigger
        return {"status": "need_bank", "message": "请先生成题库"}

    # Check stale
    current_hash = _compute_session_content_hash(note)
    if current_hash != bank_entry.get("content_hash", ""):
        return {"status": "stale", "message": "笔记内容已变化，请重新生成题库"}

    # Sample questions from bank
    all_questions = bank_entry["questions"]
    count = min(QUESTIONS_PER_QUIZ, len(all_questions))
    sampled = _sample_questions_for_attempt(all_questions, _get_quizzes_from_vocabulary(note), count)

    quiz_id = str(uuid.uuid4())

    # Save full question snapshot in the attempt so it's immune to bank rebuilds.
    # The snapshot includes answers; we strip them when returning to the frontend.
    questions_snapshot = sampled

    quiz_entry = {
        "kind": "quiz",
        "quiz_id": quiz_id,
        "bank_hash": bank_entry.get("content_hash", ""),
        "questions_snapshot": questions_snapshot,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "submission": None,
    }
    _add_quiz_to_vocabulary(note, quiz_entry)
    db.commit()

    # Return questions WITHOUT answers for the taking-quiz view
    safe_questions = []
    for q in sampled:
        safe_questions.append({
            "id": q["id"],
            "question": q["question"],
            "options": [{"id": o["id"], "text": o["text"]} for o in q.get("options", [])],
        })

    return {
        "quiz_id": quiz_id,
        "title": "本节课测验",
        "questions": safe_questions,
    }


# ── List quizzes (without answers) ──

def get_session_quizzes(session_id: str, user: User, db: DBSessionType) -> list[dict]:
    """Return list of all quiz attempts for a session, without answers."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        return []

    quizzes = _get_quizzes_from_vocabulary(note)
    result = []
    for entry in quizzes:
        snapshot = entry.get("questions_snapshot", [])
        submission = entry.get("submission")

        # Build safe questions (no answers)
        safe_questions = []
        for q in snapshot:
            safe_questions.append({
                "id": q.get("id"),
                "question": q.get("question"),
                "options": [{"id": o.get("id"), "text": o.get("text")} for o in q.get("options", [])],
            })

        score_summary = None
        if submission:
            score_summary = {
                "score": submission.get("score", 0),
                "total": submission.get("total", 0),
                "percentage": submission.get("percentage", 0),
            }

        result.append({
            "quiz_id": entry.get("quiz_id"),
            "title": "本节课测验",
            "question_count": len(snapshot),
            "questions": safe_questions,
            "generated_at": entry.get("generated_at"),
            "submitted": submission is not None,
            "score": score_summary,
        })

    return result


# ── Quiz detail ──

def get_quiz_detail(session_id: str, quiz_id: str, user: User, db: DBSessionType) -> dict:
    """Return quiz detail. If not submitted, strip answers. If submitted, return full detail."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("Quiz not found")

    entry = _get_quiz_from_vocabulary(note, quiz_id)
    if not entry:
        raise ValueError("Quiz not found")

    snapshot = entry.get("questions_snapshot", [])
    submission = entry.get("submission")

    if submission:
        # Submitted — return full detail with answers and explanations
        return {
            "quiz_id": entry.get("quiz_id"),
            "title": "本节课测验",
            "questions": snapshot,
            "generated_at": entry.get("generated_at"),
            "submission": submission,
        }
    else:
        # Not submitted — strip answers
        safe_questions = []
        for q in snapshot:
            safe_questions.append({
                "id": q.get("id"),
                "question": q.get("question"),
                "options": [{"id": o.get("id"), "text": o.get("text")} for o in q.get("options", [])],
            })

        return {
            "quiz_id": entry.get("quiz_id"),
            "title": "本节课测验",
            "questions": safe_questions,
            "generated_at": entry.get("generated_at"),
            "submission": None,
        }


# ── Submit quiz answers ──

def submit_quiz_answers(session_id: str, quiz_id: str, user: User, db: DBSessionType, answers: dict) -> dict:
    """Submit answers for a quiz attempt. Calculate score using bank answers."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("Quiz not found")

    entry = _get_quiz_from_vocabulary(note, quiz_id)
    if not entry:
        raise ValueError("Quiz not found")

    # If already submitted, return existing results
    if entry.get("submission"):
        sub = entry["submission"]
        return {
            "score": sub.get("score", 0),
            "total": sub.get("total", 0),
            "percentage": sub.get("percentage", 0),
            "results": sub.get("results", []),
        }

    # Get answers from snapshot (immune to bank rebuilds)
    snapshot = entry.get("questions_snapshot", [])

    correct_count = 0
    results = []
    for q in snapshot:
        qid = q.get("id")
        correct_answer = q.get("answer", "")
        selected = answers.get(qid, "")
        is_correct = selected == correct_answer
        if is_correct:
            correct_count += 1

        results.append({
            "question_id": qid,
            "correct": is_correct,
            "selected": selected,
            "answer": correct_answer,
            "explanation": q.get("explanation", ""),
        })

    total = len(snapshot)
    percentage = round(correct_count / total * 100, 1) if total > 0 else 0

    # Save submission
    updated_entry = dict(entry)
    updated_entry["submission"] = {
        "answers": answers,
        "score": correct_count,
        "total": total,
        "percentage": percentage,
        "results": results,
        "submitted_at": datetime.now(timezone.utc).isoformat(),
    }
    _update_quiz_in_vocabulary(note, quiz_id, updated_entry)
    db.commit()

    return {
        "score": correct_count,
        "total": total,
        "percentage": percentage,
        "results": results,
    }


# ── Delete quiz attempt ──

def delete_quiz(session_id: str, quiz_id: str, user: User, db: DBSessionType) -> dict:
    """Delete a specific quiz attempt (not the bank)."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if note:
        _remove_quiz_from_vocabulary(note, quiz_id)
        db.commit()

    return {"session_id": session_id, "quiz_id": quiz_id, "status": "deleted"}
